---
name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        ruby: ["3.0", "3.1"]
        # Ruby 3.2 is segfaulting, we need to fix that.
        # ruby: ["2.7", "3.0", "3.1", "3.2"]
        rust: ["stable"]
        include:
          - os: windows-latest
            ruby-version: mswin
            rustup-toolchain: stable
    steps:
      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rustup-toolchain: ${{ matrix.rust }}
          cache-version: v2
          bundler-cache: true
          cargo-cache: true
          cargo-cache-extra-path: |
            examples/rutie_ruby_example/tmp/
            examples/rutie_ruby_gvl_example/tmp/
            examples/rutie_rust_example/tmp/

      - name: Example tests (rutie_ruby_example)
        working-directory: examples/rutie_ruby_example
        run: bundle && bundle exec rake test

      - name: Example tests (rutie_ruby_gvl_example)
        working-directory: examples/rutie_ruby_gvl_example
        run: bundle && bundle exec rake test

      - name: Example tests (rutie_rust_example)
        working-directory: examples/rutie_rust_example
        run: cargo test

      - name: Run Rust (doc) tests
        run: cargo test --doc

      # - name: Lint rust
      #   run: cargo clippy && cargo fmt --check

      - name: Run Ruby gem tests
        run: | 
          git submodule update --init
          cd gem && rake test

